### ISSUE TITLE
does the API provide ability (method) to allow retrieve studentID based on student first name, last name, and DOB?

### ISSUE THREAD

**Issue by SupportBlumark** [TheAlphaSchoolSystemPTYLTD/online-enrolments#1]
does the API provide ability (method) to allow retrieve studentID based on student first name, last name, and DOB?
For Catholic Education, after OnBase inserts the student information into TASS, and once they are confirmed in TASS, the customer would like to be able to 'back-fill' StudentID information in OnBase.

Thanks very much.

**Comment by team-hq** [comment]
@SupportBlumark I guess you can use getEnrolledStudents.md to fetch all students and do the matching at your end. In any case I think it'll always need a pair of human eyes to go over the student data.

**Comment by scottetass** [comment]
Hi SupportBlumark,

Once a student enrolment has been processed in TASS, you can use the getEnrolledStudents endpoint, passing in the application_id and you will get back the full student record, which will include stud_code & id fields.

Thanks, Scott
