### ISSUE TITLE
Not able to upload a file through setStudentUDArea API

### ISSUE THREAD

**Issue by PITPL-Viral-Shah** [TheAlphaSchoolSystemPTYLTD/online-enrolments#79]
We tried to attach and upload a document for an existing student through API setStudentUDArea in Postman. We could attach the document few days ago with same request structure through postman but we are getting error currently.

{"__status":"invalid","__forms":{"studentudarea":{"model_intent":"","model_version":3.0,"model":"student.extendedud.1.grid","model_sequencecolumn":""}},"__msg":"The
AUDIT parameter to the setStudentEUDGrid function is required but was not passed
in.","__invalid":{},"__locks":{"strict":true,"conflictexpires":"","batch_id":"CD88C443-05B4-26D0-3B8CFD47E82C7BA4","tried":true,"invalidmsg":"Please
try
again.","status":"","conflictuserdesc":"","taken":true,"conflictuser":"","enabled":true,"timeout":2,"type":"batch","redirect":""}}

We passed the file in base64 string format as required. Can you help for the same?

**Comment by leonseremelis-tass** [comment]
Thank you for notifying us about this issue. After our internal testing, we haven't been able to reproduce it. Could you please provide us with additional information and confirm if you are still experiencing this problem? Your cooperation will greatly assist us in further investigating and resolving the issue.

**Comment by PITPL-Viral-Shah** [comment]
@leonseremelis-tass Hi, thank you for following up on this issue. We are able to upload file through setStudentUDArea API now.
