### ISSUE TITLE
Can the API support updating enrolments which weren't originally created online?

### ISSUE THREAD

**Issue by napper1** [TheAlphaSchoolSystemPTYLTD/online-enrolments#81]
Hi there,

We have come across an issue where we can't update enrolments in TASS which were paper forms and entered into TASS at some point. Our clients would like to update these in TASS through the API when they have new information (notes, documents, updated addresses, etc).

When we try to update the enrolment with a TASS student code the error message we receive is `"Enrolled student not in staging table."`

Can the API support updating these types of enrolments which weren't originally created online? We're able to update enrolments which were created via the API.

**Comment by bradftass** [comment]
Hi Ben,

Unfortunately at this stage this API can only interact with records that were created via the Online Enrolments API.  It currently requires the connection record that is set during this process.

I will note this as an enhancement request for future consideration.

**Comment by napper1** [comment]
Hi Brad, 

Sure it would be great if the API could interact with the other records as our clients are having to manually update paper applications in TASS (in some cases 100s of applications per cohort).

**Comment by bradftass** [comment]
Thanks Ben,

I appreciate the effort required in updating records that were not entered via the online enrolments process.  This would be a fundamental change to this system and needs to be considered carefully.  We have a rather large backlog, but I do have this noted for further investigation.

**Comment by napper1** [comment]
Ok thanks Brad appreciate it.
