### ISSUE TITLE
Strange response when using SetEnrolledStudents

### ISSUE THREAD

**Issue by napper1** [TheAlphaSchoolSystemPTYLTD/online-enrolments#83]
Hi,

Sometimes when using the `setEnrolledStudents` endpoint the API returns some JavaScript text:

```
<script>document.addEventListener('DOMContentLoaded', function () { if ( typeof top !== 'undefined' ) { 	top.window.location.href = 'back';} else {	window.location.href = 'back';}});</script>
```

Why is it returning this type of text? Can it be altered to return a message in JSON format? The version I'm noticing this on is 01.058.09.200. If it helps I can provide the payload used in the request privately. Thanks

**Comment by leonseremelis-tass** [comment]
Hi, thanks for reporting this. I have been able to reproduce similar behavior to what you are experiencing and have marked it as a bug. We will discuss it further internally and get it resolved as soon as possible.

**Comment by leonseremelis-tass** [comment]
A fix for this is scheduled to be in the next release v58.12

**Comment by napper1** [comment]
Great thank you.
