### ISSUE TITLE
Not able to access the Student Medical Section in TASS

### ISSUE THREAD

**Issue by PITPL-Viral-Shah** [TheAlphaSchoolSystemPTYLTD/online-enrolments#85]
![image](https://github.com/TheAlphaSchoolSystemPTYLTD/online-enrolments/assets/102034649/b573c71c-173a-41e5-942a-0de14c390101)

With our TASS Account, I am not able to access the student medical section under Medical Records > Student Information.
Is there any other way where we can check the student medical conditions?  How can we get access to the medical section? Request to guide for the same.  Thank you.

**Comment by scottetass** [comment]
Hi,

Could you please redirect your question to Customer Care?
This is not API related and customer care should be able to help you out with security related issues.

Regards, Scott
