### ISSUE TITLE
No Data in API Response

### ISSUE THREAD

**Issue by PITPL-Viral-Shah** [TheAlphaSchoolSystemPTYLTD/online-enrolments#87]
Dear TASS Support,
                                 We are trying to setup an integration with Caboolture Montessori School using TASS API configuration. We have the necessary details which are required to access the APIs. 

We are trying to call the APIs  getTitles, getGenders, getReligions, getCampuses   etc which are a GET APIs used to retrieve available values in TASS for those endpoints. 

For all the above APIs we call, we are not getting any error and we get status: 200 OK. But we are getting an empty response. Nor do we get the required response data neither do we get any other response message as well. So we are unable to figure out the issue. Kindly help with the same. Thank you

**Comment by scottetass** [comment]
Hi,

This issue has been fixed. In IIS, the default document list for the api sub-folder under the tassweb web site needed to be modified.

Another option, which does not require IIS changes, would be to modify your URL slightly and add 'index.cfm' to the end eg. **https://[domain]/tassweb/api/index.cfm** and then call the API as you currently do.

Thanks, Scott

**Comment by PITPL-Viral-Shah** [comment]
Hi @scottetass ,
                           Thank you for the solution. We tested the APIs and get the data in response now successfully. Thank you for your time and efforts.
