### ISSUE TITLE
Want to set Alternate ID field for student in TASS

### ISSUE THREAD

**Issue by PITPL-Viral-Shah** [TheAlphaSchoolSystemPTYLTD/online-enrolments#88]
We want to set the Alternate ID for student through API but could not find the field in any of the endpoints available. I entered the ID manually, saved the student. When I called the getEnroledStudents API for that student code, I got that alternate ID field with the value in response. Please find the screenshots for the same:-

![image](https://github.com/user-attachments/assets/575f1214-1612-4cd6-9c97-2a6b7ff767c4)

Field received in Response:-

![image](https://github.com/user-attachments/assets/8620baf3-b49a-4db0-9395-4646be1b11b5)

Kindly help with the same. Thank you

**Comment by scottetass** [comment]
Hi,

The ability to set a students alt_id field is available in two API endpoints.

```
data-upload-utility/setStudentDataUploadUtility

      {
        "students": [
          {
            "id": "20903",
            "alt_id": "100"
          }
        ]
      }
```

```
IdM/setStudent

      {
        "user_code": "20903",
        "alt_id": "100"
      }
```

If you are not licensed for either of these two endpoints, then there is currently no other API for setting the alt_id for a student.

Thanks, Scott

**Comment by PITPL-Viral-Shah** [comment]
Hi Scott,
                   Thank you for mentioning the API details for the Alternate ID field in TASS. Can you let me know where can we find the API documentation for the endpoints that you mentioned in the prior email?

-         data-upload-utility/setStudentDataUploadUtility

-         IdM/setStudent

We could not find the same on github:- https://github.com/TheAlphaSchoolSystemPTYLTD


Thanks and Regards,
Viral Shah

**Comment by scottetass** [comment]
Hi,

The two repositories can be found here:

https://github.com/TheAlphaSchoolSystemPTYLTD/data-upload-utility
https://github.com/TheAlphaSchoolSystemPTYLTD/IdM

They are both public repositories so you should be able to access them.

Thanks, Scott

**Comment by PITPL-Viral-Shah** [comment]
OK, Thank you for mentioning the same. I got the details at the links given.

I tried to access the APIs but got this error:-

Status 501 - Header values specify a method that is not implemented.

I wonder if there is a licence issue or something else? As I did not get access denied error.
Can you guide me? Thank you

**Comment by scottetass** [comment]
Hi,

To check if you are licensed for these modules, go into TASS.Web and navigate the menu system to open the TASS licensing page, System Admin > Utilities > TASS Licensing.

When the screen loads, click on Licensed Modules tab and check to see if you are licensed for either of those API's. Module codes for those two are API14 and API23.

If you are licensed for either of those APIs, then the next step is to check they have been setup in 'API Gateway Maintenance' (System Admin > Utilities > API Gateway Maintenance). If they haven't been set up, add them in. Ensure you set a security role as V3 endpoints require a security role allocated.

Try calling the required endpoints as you would any other V3 endpoint.

Thanks, Scott

**Comment by PITPL-Viral-Shah** [comment]
Hi @scottetass  thank you for the detailed steps to check for the API endpoint access. I logged in the portal https://api.tassweb.com.au/tassweb/index.cfm  but I found that have no access to the TASS Licensing section as you mentioned:-

![image](https://github.com/user-attachments/assets/f3e8bb49-2aa0-4a67-84a9-2016567cce74)

Can you let me know is there any option to enable that?

**Comment by scottetass** [comment]
Hi,

You'll have to find someone at the school who is a TASS administrator to check for you then or contact TASS customer support. I don't have access to school environments to check for you.

Thanks, Scott

**Comment by PITPL-Viral-Shah** [comment]
Ok, @scottetass  Thank you for all your help. I shall contact school TASS admin further.
